FROM python:3.11-slim

WORKDIR /app

# Установка системных зависимостей и Go
RUN apt-get update && apt-get install -y \
    nmap \
    gcc \
    curl \
    git \
    wget \
    golang-go \
    && rm -rf /var/lib/apt/lists/*

# Установка Go инструментов для сканирования безопасности
RUN go install github.com/projectdiscovery/katana/cmd/katana@latest 
RUN CGO_ENABLED=0 go install -v github.com/owasp-amass/amass/v5/cmd/amass@main
RUN go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest 
RUN go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest 
RUN go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest 
RUN go install -v github.com/kacakb/jsfinder@latest 
RUN go install github.com/tomnomnom/waybackurls@latest 
RUN go install github.com/OJ/gobuster/v3@latest 
RUN cp /root/go/bin/* /usr/local/bin/
RUN apt install nmap -y

ENV PATH="/root/go/bin:$PATH"

ENV PATH="/root/go/bin:$PATH"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN mkdir -p /app/reports
RUN mkdir -p /app/reports && chown -R 1000:1000 /app/reports && chmod -R 755 /app/reports

EXPOSE 8000

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
